### ISSUE TITLE
15.1.1 Versioning release candidates for continuous delivery

### ISSUE THREAD

**Issue by EduAugustoo** [ThomasVitale/cloud-native-spring-in-action#23]
Hello, Thomas.
When i update the commit-stage.yml file to use Git’s commit hash the pipeline fails. At the “OCI image vulnerability scanning” step, the following message appears:
`Executing: grype -o sarif --fail-on high ghcr.io/eduaugustoo/catalog-service:0f9acff30aa3d11cfdb335547c5ff14a6e855192 1 error occurred: * failed to catalog: could not fetch image "ghcr.io/eduaugustoo/catalog-service:0f9acff30aa3d11cfdb335547c5ff14a6e855192": unable to use DockerDaemon source: pull failed: Error response from daemon: manifest unknown`
And at the following step, "Upload vulnerability report", it gives the error below:
`Processing sarif files: ["./results.sarif"] Error: Unexpected end of JSON input SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:190:24) at uploadFiles (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:267:9) at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:139:18) at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:49:30) at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:71:9)`

I am using maven instead of gradle, and my commit-stage.yml is as follows:
```
name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eduaugustoo/catalog-service
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: maven
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          chmod +x mvnw
          ./mvnw install
      - name: Validate Kubernetes manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.23.4
          kubeval: 0.16.1
          command: |
            kustomize build k8s | kubeval --strict -

  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: maven
      - name: Build container image
        run: |
          chmod +x mvnw
          ./mvnw spring-boot:build-image "-Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
      - name: OCI image vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Log into container registry
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Publish container image (latest)
        run: |
          docker tag \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
```

Could yout help me out?
