### ISSUE TITLE
Change kubeval by kubeconform

### ISSUE THREAD

**Issue by ahmedkhabkhab** [ThomasVitale/cloud-native-spring-in-action#33]
kubeval is no longer maintained. Instead of doing a workaround by providing the schema URL, it would be better to use another tool like [kubeconform](https://github.com/yannh/kubeconform).

```
      - name: Validate Kubernetes manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.26.1
          kubeconform: 0.5.0
          command: |
            kubeconform -strict -debug k8s
```

-debug is not needed. I just added it to show the schema URLs used to validate k8s yaml files
