### ISSUE TITLE
Chapter 2 bug in commit-stage.yaml example

### ISSUE THREAD

**Issue by mskalbania** [ThomasVitale/cloud-native-spring-in-action#38]
Hi,
Looks like there is a bug in commit-stage.yaml file.
Security scans should be run **after** running gradle build and dependency resolution.
```yaml
      - name: Build, unit tests and integration tests
        run: ./gradlew build
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          severity-cutoff: critical
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
```
Running them before causes dependencies to not be scanned and always shows that no vulnerabilities were found.
