### ISSUE TITLE
edge-service unable to connect to Redis wen running inside of a K8s cluster

### ISSUE THREAD

**Issue by shantdashjian** [ThomasVitale/cloud-native-spring-in-action#71]
# Description: 
edge-service is unable to connect to Redis wen running inside of a K8s cluster. 

## Problem:

Starting with Chapter09, in the `edge-service/k8s/deployment.yml`, we set:
```
            - name: SPRING_REDIS_HOST
              value: polar-redis
```

This value is supposed to be used when deploying to K8s cluster. But we are not currently using it. So in `src/main/resources/application.yml`, we still have:
```
spring:
    data:
      redis:
        connect-timeout: 2s
        host: localhost
        port: 6379
        timeout: 1s
```

This is causing an issue when running the system in K8s. The edge-service is unable to connect to Redis because it cannot find it. 

## Solution:
```
spring:
    data:
      redis:
        connect-timeout: 2s
        host: ${SPRING_REDIS_HOST:localhost}
        port: 6379
        timeout: 1s
```
